version: '3'

services:
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '127.0.0.1:27017:27017'

  redis:
    image: redis
    volumes:
      - ./data/redis:/data/redis
    ports:
      - '127.0.0.1:6379:6379'

volumes:
  mongo-data: